total_rows: 100000000
select_rows: 1000
select_cols: 10
write_batch_size: 100000
measurement_time_secs: 30
warmup_time_secs: 2
sample_size: 50
backend:
  # valkey_iothreads:
  #   image: "valkey/valkey:8.1"
  #   command: ["valkey-server", "--save", "", "--appendonly", "no", "--io-threads", "4", "--io-threads-do-reads", "yes"]
  #   wait_log: "Ready to accept connections"
  #   read_mode: hgetall
  #   # cgroup_memory_mb: 4096            # cap container RAM; omit = unlimited
  valkey_default:
    image: "valkey/valkey:8.1"
    command: ["valkey-server", "--save", "", "--appendonly", "no"]
    wait_log: "Ready to accept connections"
    read_mode: hgetall
