write_batch_size: 100000
measurement_time_secs: 30
warmup_time_secs: 2
sample_size: 50
backend:
  # redis_iothreads:
  #   image: "redis:8.10.2"
  #   command: ["redis-server", "--save", "", "--appendonly", "no", "--io-threads", "4", "--io-threads-do-reads", "yes"]
  #   wait_log: "Ready to accept connections"
  #   read_mode: hmget
    # cgroup_memory_mb: 4096            # cap container RAM; omit = unlimited
  redis_default:
    image: "redis:8.10.2"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    wait_log: "Ready to accept connections"
    read_mode: hmget
